# This script plots summary statistics from the populations VCF output file.
# The summary statistics need to be provided by a file generated by parse_VCF
# Cyril Matthey-Doret
# 01.05.2017


args = commandArgs(trailingOnly=TRUE)
setwd(args[1])

plot_popstats <- function(sum_file,stats){
  # sum_file: path to the input summary file
  # parameter to be plotted. Needs to be a colname
  sex_palette <- c('pink','blue')  # Color palette used to represent sex
  sum_table <- read.table(file=sum_file,sep='\t',header=T)  # reading input file
  sum_table$SEX <- sapply(sum_table$INDV,function(x) substr(x,8,8))  # Extracting sex info from sample name
  sum_table$FAMILY <- sapply(sum_table$INDV,function(x) substr(x,4,4))  # Extracting family info from sample name
  sum_table$INDV <- sapply(sum_table$INDV,function(x) substr(x,4,6))  # Shortening sample name
  if(stats=='PROP'){
   sum_table$PROP <- sum_table$O.HOM./ sum_table$E.HOM.
  }
  pl_row <- length(unique(sum_table$FAMILY)) / 2  # Plots spread over 2 rows
  par(mfrow=c(2,pl_row))
  sum_table <- sum_table[with(sum_table, order(FAMILY,sum_table[,stats])), ]
  for(f in unique(sum_table$FAMILY)){
    subt <- sum_table[sum_table$FAMILY==f,]
    barplot(height = subt[,stats],
            names.arg = subt$INDV,
            col =  sex_palette[as.factor(subt$SEX)],main=f)
    MF <- mean(subt[subt$SEX=='F',stats]); SF <- sd(subt[subt$SEX=='F',stats])
    MM <- mean(subt[subt$SEX=='M',stats]); SM <- sd(subt[subt$SEX=='M',stats])
    abline(h = MF,col="pink")
    # abline(h = MF-SF,col="pink");abline(h = MF+SF,col="pink",lty=2)
    abline(h = MM,col="blue")
    # abline(h = MM-SM,col="blue",lty=2);abline(h = MM+SM,col="blue",lty=2)
    par(xpd=NA)
    scoef <- nrow(subt)/20
    polygon(x=c(-5,-3,-3,-5)*scoef,y=c(MF-SF,MF-SF,MF+SF,MF+SF), 
            col=rgb(1, 0.75, 0.8,0.6),lty = 1,border=NA)
    polygon(x=c(-3,-1,-1,-3)*scoef,y=c(MM-SM,MM-SM,MM+SM,MM+SM), 
            col=rgb(0, 0, 1,0.6),lty = 1,border=NA)
    par(xpd=FALSE)
  }
}

param_space <- seq(75,85,5)
ref_table <- read.table(file="vcftools/summary_r-75",sep='\t',header=T)
out_table <- matrix(nrow = length(param_space),ncol = 7)
out_table <- as.data.frame.array(out_table)
colnames(out_table) <- c("R","O.HOM.","E.HOM.","N_SITES","F","MEAN_DEPTH","PROP")
out_table$R <- param_space
for(p in param_space){
  for(param in c("O.HOM.","E.HOM.","N_SITES","F","MEAN_DEPTH","PROP")){
    if(param %in% c('F','MEAN_DEPTH','PROP')){
      pdf(paste0("vcftools/",param,"_r-",p,".pdf"),width = 9)
      plot_popstats(paste0("vcftools/summary_r-",p),param)
      dev.off()
    }
    tmp_tbl <- read.table(paste0("vcftools/summary_r-",p),header = T,sep="\t")
    tmp_tbl$PROP <- tmp_tbl$O.HOM./ tmp_tbl$E.HOM.
    out_table[out_table$R==p,param] <- mean(tmp_tbl[,param])
  }
}
out_table <- data.frame(lapply(out_table, function(y) if(is.numeric(y)) round(y, 2) else y))
colnames(out_table) <- c("r parameter","obs.hom.","exp.hom.","n.sites","inbreed.coef.","mean depth","obs./exp. hom.")
write.table(out_table,file='vcftools/vcf_sumtable.csv',col.names = T,quote = F,row.names = F,sep=',')
system("cp vcftools/vcf_sumtable.csv vcftools/F_r-75.pdf ../../reports/lab_book/")

